[tool.poetry]
name = "dockerfiles"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
demisto-sdk = {git = "https://github.com/demisto/demisto-sdk.git", rev = "CIAC-11199/support-ValidateContent-script"}
demisto-py = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
