_comment: MITRE ATT&CK Technique to Tactic Mapping
_description: Comprehensive mapping of MITRE ATT&CK techniques to their primary tactics
_source: MITRE ATT&CK Framework v15 (https://attack.mitre.org/)
_last_updated: '2025-12-03'
_coverage: Enterprise ATT&CK Matrix - All 14 Tactics
technique_to_tactic:
  T1595: TA0043
  T1595.001: TA0043
  T1595.002: TA0043
  T1592: TA0043
  T1592.001: TA0043
  T1592.002: TA0043
  T1592.003: TA0043
  T1592.004: TA0043
  T1589: TA0043
  T1589.001: TA0043
  T1589.002: TA0043
  T1589.003: TA0043
  T1590: TA0043
  T1590.001: TA0043
  T1590.002: TA0043
  T1590.003: TA0043
  T1590.004: TA0043
  T1590.005: TA0043
  T1590.006: TA0043
  T1591: TA0043
  T1591.001: TA0043
  T1591.002: TA0043
  T1591.003: TA0043
  T1591.004: TA0043
  T1598: TA0043
  T1598.001: TA0043
  T1598.002: TA0043
  T1598.003: TA0043
  T1597: TA0043
  T1597.001: TA0043
  T1597.002: TA0043
  T1596: TA0043
  T1596.001: TA0043
  T1596.002: TA0043
  T1596.003: TA0043
  T1596.004: TA0043
  T1596.005: TA0043
  T1593: TA0043
  T1593.001: TA0043
  T1593.002: TA0043
  T1594: TA0043
  T1583: TA0042
  T1583.001: TA0042
  T1583.002: TA0042
  T1583.003: TA0042
  T1583.004: TA0042
  T1583.005: TA0042
  T1583.006: TA0042
  T1583.007: TA0042
  T1583.008: TA0042
  T1586: TA0042
  T1586.001: TA0042
  T1586.002: TA0042
  T1586.003: TA0042
  T1584: TA0042
  T1584.001: TA0042
  T1584.002: TA0042
  T1584.003: TA0042
  T1584.004: TA0042
  T1584.005: TA0042
  T1584.006: TA0042
  T1584.007: TA0042
  T1587: TA0042
  T1587.001: TA0042
  T1587.002: TA0042
  T1587.003: TA0042
  T1587.004: TA0042
  T1585: TA0042
  T1585.001: TA0042
  T1585.002: TA0042
  T1585.003: TA0042
  T1588: TA0042
  T1588.001: TA0042
  T1588.002: TA0042
  T1588.003: TA0042
  T1588.004: TA0042
  T1588.005: TA0042
  T1588.006: TA0042
  T1608: TA0042
  T1608.001: TA0042
  T1608.002: TA0042
  T1608.003: TA0042
  T1608.004: TA0042
  T1608.005: TA0042
  T1608.006: TA0042
  T1189: TA0001
  T1190: TA0001
  T1133: TA0003
  T1200: TA0001
  T1566: TA0001
  T1566.001: TA0001
  T1566.002: TA0001
  T1566.003: TA0001
  T1566.004: TA0001
  T1091: TA0008
  T1195: TA0001
  T1195.001: TA0001
  T1195.002: TA0001
  T1195.003: TA0001
  T1199: TA0001
  T1078: TA0005
  T1078.001: TA0001
  T1078.002: TA0001
  T1078.003: TA0001
  T1078.004: TA0001
  T1059: TA0002
  T1059.001: TA0002
  T1059.002: TA0002
  T1059.003: TA0002
  T1059.004: TA0002
  T1059.005: TA0002
  T1059.006: TA0002
  T1059.007: TA0002
  T1059.008: TA0002
  T1059.009: TA0002
  T1609: TA0002
  T1610: TA0005
  T1203: TA0002
  T1559: TA0002
  T1559.001: TA0002
  T1559.002: TA0002
  T1559.003: TA0002
  T1106: TA0002
  T1053: TA0004
  T1053.001: TA0002
  T1053.002: TA0002
  T1053.003: TA0002
  T1053.005: TA0002
  T1053.006: TA0002
  T1053.007: TA0002
  T1129: TA0002
  T1072: TA0008
  T1569: TA0002
  T1569.001: TA0002
  T1569.002: TA0002
  T1204: TA0002
  T1204.001: TA0002
  T1204.002: TA0002
  T1204.003: TA0002
  T1047: TA0002
  T1098: TA0003
  T1098.001: TA0003
  T1098.002: TA0003
  T1098.003: TA0003
  T1098.004: TA0003
  T1098.005: TA0003
  T1197: TA0003
  T1547: TA0003
  T1547.001: TA0003
  T1547.002: TA0003
  T1547.003: TA0003
  T1547.004: TA0003
  T1547.005: TA0003
  T1547.006: TA0003
  T1547.007: TA0003
  T1547.008: TA0003
  T1547.009: TA0003
  T1547.010: TA0003
  T1547.012: TA0003
  T1547.013: TA0003
  T1547.014: TA0003
  T1547.015: TA0003
  T1037: TA0003
  T1037.001: TA0003
  T1037.002: TA0003
  T1037.003: TA0003
  T1037.004: TA0003
  T1037.005: TA0003
  T1176: TA0003
  T1554: TA0003
  T1136: TA0003
  T1136.001: TA0003
  T1136.002: TA0003
  T1136.003: TA0003
  T1543: TA0003
  T1543.001: TA0003
  T1543.002: TA0003
  T1543.003: TA0003
  T1543.004: TA0003
  T1546: TA0004
  T1546.001: TA0003
  T1546.002: TA0003
  T1546.003: TA0003
  T1546.004: TA0003
  T1546.005: TA0003
  T1546.006: TA0003
  T1546.007: TA0003
  T1546.008: TA0003
  T1546.009: TA0003
  T1546.010: TA0003
  T1546.011: TA0003
  T1546.012: TA0003
  T1546.013: TA0003
  T1546.014: TA0003
  T1546.015: TA0003
  T1546.016: TA0003
  T1574: TA0004
  T1574.001: TA0003
  T1574.002: TA0003
  T1574.004: TA0003
  T1574.005: TA0003
  T1574.006: TA0003
  T1574.007: TA0003
  T1574.008: TA0003
  T1574.009: TA0003
  T1574.010: TA0003
  T1574.011: TA0003
  T1574.012: TA0003
  T1574.013: TA0003
  T1525: TA0003
  T1556: TA0006
  T1556.001: TA0003
  T1556.002: TA0003
  T1556.003: TA0003
  T1556.004: TA0003
  T1556.005: TA0003
  T1556.006: TA0003
  T1556.007: TA0003
  T1556.008: TA0003
  T1137: TA0003
  T1137.001: TA0003
  T1137.002: TA0003
  T1137.003: TA0003
  T1137.004: TA0003
  T1137.005: TA0003
  T1137.006: TA0003
  T1542: TA0005
  T1542.001: TA0003
  T1542.002: TA0003
  T1542.003: TA0003
  T1542.004: TA0003
  T1542.005: TA0003
  T1505: TA0003
  T1505.001: TA0003
  T1505.002: TA0003
  T1505.003: TA0003
  T1505.004: TA0003
  T1505.005: TA0003
  T1205: TA0011
  T1205.001: TA0003
  T1205.002: TA0003
  T1548: TA0004
  T1548.001: TA0004
  T1548.002: TA0004
  T1548.003: TA0004
  T1548.004: TA0004
  T1134: TA0004
  T1134.001: TA0004
  T1134.002: TA0004
  T1134.003: TA0004
  T1134.004: TA0004
  T1134.005: TA0004
  T1484: TA0004
  T1484.001: TA0004
  T1484.002: TA0004
  T1611: TA0004
  T1068: TA0004
  T1055: TA0005
  T1055.001: TA0004
  T1055.002: TA0004
  T1055.003: TA0004
  T1055.004: TA0004
  T1055.005: TA0004
  T1055.008: TA0004
  T1055.009: TA0004
  T1055.011: TA0004
  T1055.012: TA0004
  T1055.013: TA0004
  T1055.014: TA0004
  T1055.015: TA0004
  T1612: TA0005
  T1140: TA0005
  T1006: TA0005
  T1480: TA0005
  T1480.001: TA0005
  T1211: TA0005
  T1222: TA0005
  T1222.001: TA0005
  T1222.002: TA0005
  T1564: TA0005
  T1564.001: TA0005
  T1564.002: TA0005
  T1564.003: TA0005
  T1564.004: TA0005
  T1564.005: TA0005
  T1564.006: TA0005
  T1564.007: TA0005
  T1564.008: TA0005
  T1564.009: TA0005
  T1564.010: TA0005
  T1564.011: TA0005
  T1564.012: TA0005
  T1562: TA0005
  T1562.001: TA0005
  T1562.002: TA0005
  T1562.003: TA0005
  T1562.004: TA0005
  T1562.006: TA0005
  T1562.007: TA0005
  T1562.008: TA0005
  T1562.009: TA0005
  T1562.010: TA0005
  T1562.011: TA0005
  T1562.012: TA0005
  T1070: TA0005
  T1070.001: TA0005
  T1070.002: TA0005
  T1070.003: TA0005
  T1070.004: TA0005
  T1070.005: TA0005
  T1070.006: TA0005
  T1070.007: TA0005
  T1070.008: TA0005
  T1070.009: TA0005
  T1202: TA0005
  T1036: TA0005
  T1036.001: TA0005
  T1036.002: TA0005
  T1036.003: TA0005
  T1036.004: TA0005
  T1036.005: TA0005
  T1036.006: TA0005
  T1036.007: TA0005
  T1036.008: TA0005
  T1036.009: TA0005
  T1578: TA0005
  T1578.001: TA0005
  T1578.002: TA0005
  T1578.003: TA0005
  T1578.004: TA0005
  T1578.005: TA0005
  T1112: TA0005
  T1601: TA0005
  T1601.001: TA0005
  T1601.002: TA0005
  T1599: TA0005
  T1599.001: TA0005
  T1027: TA0005
  T1027.001: TA0005
  T1027.002: TA0005
  T1027.003: TA0005
  T1027.004: TA0005
  T1027.005: TA0005
  T1027.006: TA0005
  T1027.007: TA0005
  T1027.008: TA0005
  T1027.009: TA0005
  T1027.010: TA0005
  T1027.011: TA0005
  T1027.013: TA0005
  T1620: TA0005
  T1207: TA0005
  T1014: TA0005
  T1218: TA0005
  T1218.001: TA0005
  T1218.002: TA0005
  T1218.003: TA0005
  T1218.004: TA0005
  T1218.005: TA0005
  T1218.007: TA0005
  T1218.008: TA0005
  T1218.009: TA0005
  T1218.010: TA0005
  T1218.011: TA0005
  T1218.012: TA0005
  T1218.013: TA0005
  T1218.014: TA0005
  T1216: TA0005
  T1216.001: TA0005
  T1553: TA0005
  T1553.001: TA0005
  T1553.002: TA0005
  T1553.003: TA0005
  T1553.004: TA0005
  T1553.005: TA0005
  T1553.006: TA0005
  T1127: TA0005
  T1127.001: TA0005
  T1535: TA0005
  T1550: TA0008
  T1550.001: TA0005
  T1550.002: TA0005
  T1550.003: TA0005
  T1550.004: TA0005
  T1497: TA0007
  T1497.001: TA0005
  T1497.002: TA0005
  T1497.003: TA0005
  T1600: TA0005
  T1600.001: TA0005
  T1600.002: TA0005
  T1220: TA0005
  T1622: TA0007
  T1110: TA0006
  T1110.001: TA0006
  T1110.002: TA0006
  T1110.003: TA0006
  T1110.004: TA0006
  T1555: TA0006
  T1555.001: TA0006
  T1555.002: TA0006
  T1555.003: TA0006
  T1555.004: TA0006
  T1555.005: TA0006
  T1555.006: TA0006
  T1212: TA0006
  T1187: TA0006
  T1606: TA0006
  T1606.001: TA0006
  T1606.002: TA0006
  T1056: TA0009
  T1056.001: TA0006
  T1056.002: TA0006
  T1056.003: TA0006
  T1056.004: TA0006
  T1557: TA0009
  T1557.001: TA0006
  T1557.002: TA0006
  T1557.003: TA0006
  T1040: TA0007
  T1003: TA0006
  T1003.001: TA0006
  T1003.002: TA0006
  T1003.003: TA0006
  T1003.004: TA0006
  T1003.005: TA0006
  T1003.006: TA0006
  T1003.007: TA0006
  T1003.008: TA0006
  T1528: TA0006
  T1558: TA0006
  T1558.001: TA0006
  T1558.002: TA0006
  T1558.003: TA0006
  T1558.004: TA0006
  T1539: TA0006
  T1111: TA0006
  T1621: TA0006
  T1552: TA0006
  T1552.001: TA0006
  T1552.002: TA0006
  T1552.003: TA0006
  T1552.004: TA0006
  T1552.005: TA0006
  T1552.006: TA0006
  T1552.007: TA0006
  T1552.008: TA0006
  T1087: TA0007
  T1087.001: TA0007
  T1087.002: TA0007
  T1087.003: TA0007
  T1087.004: TA0007
  T1010: TA0007
  T1217: TA0007
  T1580: TA0007
  T1538: TA0007
  T1526: TA0007
  T1613: TA0007
  T1482: TA0007
  T1083: TA0007
  T1615: TA0007
  T1046: TA0007
  T1135: TA0007
  T1201: TA0007
  T1120: TA0007
  T1069: TA0007
  T1069.001: TA0007
  T1069.002: TA0007
  T1069.003: TA0007
  T1057: TA0007
  T1012: TA0007
  T1018: TA0007
  T1518: TA0007
  T1518.001: TA0007
  T1082: TA0007
  T1614: TA0007
  T1614.001: TA0007
  T1016: TA0007
  T1016.001: TA0007
  T1016.002: TA0007
  T1049: TA0007
  T1033: TA0007
  T1007: TA0007
  T1124: TA0007
  T1210: TA0008
  T1534: TA0008
  T1570: TA0008
  T1563: TA0008
  T1563.001: TA0008
  T1563.002: TA0008
  T1021: TA0008
  T1021.001: TA0008
  T1021.002: TA0008
  T1021.003: TA0008
  T1021.004: TA0008
  T1021.005: TA0008
  T1021.006: TA0008
  T1021.007: TA0008
  T1021.008: TA0008
  T1080: TA0008
  T1560: TA0009
  T1560.001: TA0009
  T1560.002: TA0009
  T1560.003: TA0009
  T1123: TA0009
  T1119: TA0009
  T1185: TA0009
  T1115: TA0009
  T1530: TA0009
  T1602: TA0009
  T1602.001: TA0009
  T1602.002: TA0009
  T1213: TA0009
  T1213.001: TA0009
  T1213.002: TA0009
  T1213.003: TA0009
  T1005: TA0009
  T1039: TA0009
  T1025: TA0009
  T1074: TA0009
  T1074.001: TA0009
  T1074.002: TA0009
  T1114: TA0009
  T1114.001: TA0009
  T1114.002: TA0009
  T1114.003: TA0009
  T1113: TA0009
  T1125: TA0009
  T1071: TA0011
  T1071.001: TA0011
  T1071.002: TA0011
  T1071.003: TA0011
  T1071.004: TA0011
  T1092: TA0011
  T1132: TA0011
  T1132.001: TA0011
  T1132.002: TA0011
  T1001: TA0011
  T1001.001: TA0011
  T1001.002: TA0011
  T1001.003: TA0011
  T1568: TA0011
  T1568.001: TA0011
  T1568.002: TA0011
  T1568.003: TA0011
  T1573: TA0011
  T1573.001: TA0011
  T1573.002: TA0011
  T1008: TA0011
  T1105: TA0011
  T1104: TA0011
  T1095: TA0011
  T1571: TA0011
  T1572: TA0011
  T1090: TA0011
  T1090.001: TA0011
  T1090.002: TA0011
  T1090.003: TA0011
  T1090.004: TA0011
  T1219: TA0011
  T1102: TA0011
  T1102.001: TA0011
  T1102.002: TA0011
  T1102.003: TA0011
  T1020: TA0010
  T1020.001: TA0010
  T1030: TA0010
  T1048: TA0010
  T1048.001: TA0010
  T1048.002: TA0010
  T1048.003: TA0010
  T1041: TA0010
  T1011: TA0010
  T1011.001: TA0010
  T1052: TA0010
  T1052.001: TA0010
  T1567: TA0010
  T1567.001: TA0010
  T1567.002: TA0010
  T1567.003: TA0010
  T1567.004: TA0010
  T1029: TA0010
  T1537: TA0010
  T1531: TA0040
  T1485: TA0040
  T1486: TA0040
  T1565: TA0040
  T1565.001: TA0040
  T1565.002: TA0040
  T1565.003: TA0040
  T1491: TA0040
  T1491.001: TA0040
  T1491.002: TA0040
  T1561: TA0040
  T1561.001: TA0040
  T1561.002: TA0040
  T1499: TA0040
  T1499.001: TA0040
  T1499.002: TA0040
  T1499.003: TA0040
  T1499.004: TA0040
  T1657: TA0040
  T1495: TA0040
  T1490: TA0040
  T1498: TA0040
  T1498.001: TA0040
  T1498.002: TA0040
  T1496: TA0040
  T1489: TA0040
  T1529: TA0040
