jobs:
  docker_build:
    docker:
      - image: devdemisto/dockerbuild:1.0.0.14172
    steps:
      - checkout
      - run:
          name: Validate Approved Licenses File
          command: python -m jsonschema -i docker/approved_licenses.json docker/approved_licenses.schema.json
      - run:
          name: Validate Dependabot Config
          command: ./docker/verify_dependabot.sh
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - 46:c2:72:91:9d:0e:2d:3c:93:d6:6c:12:31:df:8e:db
      - run:
          name: Build Docker Images
          command: |
            ./docker/build_docker.sh
      - store_artifacts:
          path: artifacts
          destination: docker_images
  update_repo_info:
    docker:
      - image: devdemisto/dockerbuild:1.0.0.56
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - b1:6a:a6:66:d3:20:c5:eb:0d:00:5a:17:04:3b:89:47
      - run:
          name: Update Docker Repo Info
          command: |
            ./docker/update-repository-info.sh
workflows:
  version: 2
  full_build:
    jobs:
      - docker_build
  repo_inf:
    jobs:
      - update_repo_info
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master