jobs:
  docker_build:
    docker:
      - image: devdemisto/dockerbuild:1.0.0.25778
    environnement:
      REVISION: << pipeline.number >>
    steps:
      - checkout
      - run:
          name: Validate Approved Licenses File
          command: python -m jsonschema -i docker/approved_licenses.json docker/approved_licenses.schema.json
      - run:
          name: Validate Dependabot Config
          command: ./docker/verify_dependabot.sh
      - setup_remote_docker:
          version: 20.10.6
      - add_ssh_keys:
          fingerprints:
            - 46:c2:72:91:9d:0e:2d:3c:93:d6:6c:12:31:df:8e:db
      - run:
          name: Run Ironabnk Unit Tests
          command: |
            if [[ ! $(which pyenv) ]] && [[ -n "${CIRCLECI}" ]]; then 
                echo "pyenv not found. setting up necessary env for pyenv on circle ci";\
                export PATH="$HOME/.pyenv/bin:$PATH"
                eval "$(pyenv init -)"
            fi

            pyenv versions
            pyenv local 3.9.0
            pip install pipenv==2021.5.29
            pipenv install --dev
            pipenv run pytest ironbank -v
      - run:
          name: Build Docker Images
          command: |
            ./docker/build_docker.sh
          no_output_timeout: 60m
      - store_artifacts:
          path: artifacts
          destination: docker_images
      - run:
          name: Build Ironbank Docker Images
          command: |
            pipenv run ./ironbank/build_ironbank_docker.sh
      - store_artifacts:
          path: artifacts
          destination: ironbank_docker_images
  docker_build_arm:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    environnement:
      REVISION: << pipeline.number >>
    steps:
      - checkout
      - run: pip install pipenv jsonschema requests
      - run:
          name: Validate Approved Licenses File
          command: python -m jsonschema -i docker/approved_licenses.json docker/approved_licenses.schema.json
      - run:
          name: Validate Dependabot Config
          command: ./docker/verify_dependabot.sh
      - add_ssh_keys:
          fingerprints:
            - 46:c2:72:91:9d:0e:2d:3c:93:d6:6c:12:31:df:8e:db
      # - run:
      #     name: Run Ironabnk Unit Tests
      #     command: |
      #       if [[ ! $(which pyenv) ]] && [[ -n "${CIRCLECI}" ]]; then 
      #           echo "pyenv not found. setting up necessary env for pyenv on circle ci";\
      #           export PATH="$HOME/.pyenv/bin:$PATH"
      #           eval "$(pyenv init -)"
      #       fi

      #       pyenv versions
      #       pip install pipenv==2021.5.29
      #       pipenv install --dev
      #       pipenv run pytest ironbank -v
      - run:
          name: Build Docker Images
          command: |
            ./docker/build_docker.sh
          no_output_timeout: 60m
      - store_artifacts:
          path: artifacts
          destination: docker_images
      # - run:
      #     name: Build Ironbank Docker Images
      #     command: |
      #       pipenv run ./ironbank/build_ironbank_docker.sh --python 3.9
      - store_artifacts:
          path: artifacts
          destination: ironbank_docker_images
workflows:
  version: 2
  full_build:
    jobs:
      - docker_build
      - docker_build_arm