jobs:
  docker_build:
    docker:
      - image: devdemisto/dockerbuild:1.0.0.43365
    steps:
      - checkout
      - run:
          name: Validate Approved Licenses File
          command: python -m jsonschema -i docker/approved_licenses.json docker/approved_licenses.schema.json
      - run:
          name: Validate Dependabot Config
          command: ./docker/verify_dependabot.sh
      - setup_remote_docker:
          version: 20.10.17
      - add_ssh_keys:
          fingerprints:
            - 14:9b:f7:c3:6a:d7:bd:34:8d:d6:3f:a7:68:d1:d6:af
      - run:
          name: Run Ironbank Unit Tests
          command: |
            if [[ ! $(which pyenv) ]] && [[ -n "${CIRCLECI}" ]]; then 
                echo "pyenv not found. setting up necessary env for pyenv on circle ci";\
                export PATH="$HOME/.pyenv/bin:$PATH"
                eval "$(pyenv init -)"
            fi

            pyenv versions
            pyenv local 3.9.0
            pip install pipenv==2021.5.29
            pipenv install --dev
            pipenv run pytest ironbank -v
      - run:
          name: Build Docker Images
          command: |
            ./docker/build_docker.sh
          no_output_timeout: 60m
      - store_artifacts:
          path: artifacts
          destination: docker_images
      - run:
          name: Build Ironbank Docker Images
          command: |
            pipenv run ./ironbank/build_ironbank_docker.sh --python 3.9
      - store_artifacts:
          path: artifacts
          destination: ironbank_docker_images
workflows:
  version: 2
  full_build:
    jobs:
      - docker_build