[tool.poetry]
name = "dockerfiles"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
parse-emails = {git = "https://github.com/demisto/parse-emails.git", rev = "4800ff11a3e94fb129f8ff92d424b79794d36249"}
rtfde = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
