variables:
  CURRENT_BRANCH_NAME: "dockerfiles-upload" # FIXME $INFRA_BRANCH

include:
  - file: "/.gitlab/ci/dockerfiles/.gitlab-ci.yml"
    ref: "dockerfiles-upload" # FIXME $INFRA_BRANCH
    project: "${CI_PROJECT_NAMESPACE}/infra"
