variables:
  CURRENT_BRANCH_NAME: remove_clone_content_test_conf

include:
  - file: "/.gitlab/ci/dockerfiles/.gitlab-ci.yml"
    ref: remove_clone_content_test_conf
    project: "${CI_PROJECT_NAMESPACE}/infra"
