variables:
  GH_BRANCH: $CI_COMMIT_BRANCH
  GH_COMMIT: $CI_COMMIT_SHA
trigger_job:
  trigger:
    strategy: depend
    project: ${CI_PROJECT_NAMESPACE}/dockerfiles-cicd
    branch: only_fail_not_master

