variables:
  CURRENT_BRANCH_NAME: "test_ssl_connection_python2"

include:
  - file: "/.gitlab/ci/dockerfiles/.gitlab-ci.yml"
    ref: "test_ssl_connection_python2"
    project: "${CI_PROJECT_NAMESPACE}/infra"
