variables:  # comment
  GH_BRANCH: $CI_COMMIT_BRANCH
  GH_COMMIT: $CI_COMMIT_SHA
trigger_job:
  except:
    - master
  trigger:
    strategy: depend
    project: ${CI_PROJECT_NAMESPACE}/dockerfiles-cicd

