[tool.poetry]
name = "demisto-sdk-docker"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12"
demisto-sdk = "1.38.13"
referencing = "~0.35.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
