[tool.poetry]
name = "ml"
version = "0.1.0"
description = ""
authors = ["Demisto <demisto@demisto.com>"]
readme = "README.md"


[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cpu/"
priority = "explicit"


[tool.poetry.dependencies]
python = "~3.12"
fasttext = "*"
numpy = "*"
scikit-learn = "*"
pandas = "*"
nltk = "*"
lime = "*"
tabulate = "*"
pycryptodome = "*"
spacy = "*"
fsspec = "*"
dill = "*"
catboost = "*"
langdetect = "*"
onnx = "*"
onnxruntime = "*"
transformers = "*"
setuptools = ">78.1.1"
torch = {version = "*", extras = ["cpu"], source="pytorch"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
